%% PROGRAM INPUT STARTS

% function []=film(action)

%% UNCOMMENT LATER
%% If Nothing Entered

% if nargin < 1 % on start without input variables run initialize code
%     action = 'initialize';
% end
%% UNCOMMENT LATER

%% Program Interface: 'initialize' (START HERE FOR ANALYSIS)

%% COMMENT LATER
clc;clear;clearvars;close;
%% COMMENT ENDS

LFOSRVersion=3.41;

%% UNCOMMENT
% if strcmp(action,'initialize')
%% UNCOMMENT ENDS    

    % Display user option selection

    disp(['LFOSR Film Routine Version ',num2str(LFOSRVersion)])
    disp(' User Option Selection')
    disp(' ')
    disp('  1 - Standard Option (default)')
    disp('  2 - Power Option')
    disp('  3 - Display Maximum Reflectivity Option')
    disp('  4 - Bio Sensor Option')
    disp('  5 - Spectral Photometer Filter Option')
    disp('  6 - Propagation Map Option')
    disp('  7 - Reflected | Transmitted | Absorbed Area')
    disp('  8 - Non-polarized Light Source')
    disp('  9 - Textured Reflection')
    disp(' ')
    user_option=input('Please select User Option (1 - default)-> ','s');

    %% If nothing is entered 1 is assumed as default
    
    if isempty(user_option)
        user_option='1';
    end

    %% 

    % This allows users to enter "exit, quit, or q" to quit the LFOSR routine
    %   all other text entrys result in error
    
    if ischar(user_option) && (strcmp(user_option,'quit')||strcmp(user_option,'q')||strcmp(user_option,'exit'))
        return
    elseif ischar(user_option) && isempty(str2double(user_option))
        error('Invalide User Option Entry')
    end

    user_option=str2double(user_option); %converts to number for option check

    %
    % This is the option selection to resolve user input to avaiable options
    %
    if user_option==1
        user_selection='none';
        user_run=0;
    elseif user_option==2
        user_selection='power';
        user_run=1;
    elseif user_option==3
        user_selection='max';
        user_run=1;
    elseif user_option==4
        user_selection='biosensor';
        user_run=1;
    elseif user_option==5
        user_selection='specphoto';
        user_run=1;
    elseif user_option==6
        user_selection='propagation';
        user_run=1;
    elseif user_option==7
        user_selection='area';
        user_run=1;
    elseif user_option==8
        user_selection='nonpolarized';
        user_run=1;
    elseif user_option==9
        user_selection='textured';
        user_run=1;
    else
        error('Incorrect User Option')
    end
    %%%%%%%%%%%%%%%%% SUBROUTINE PATH INPUT %%%%%%%%%%%%%%%%%%%%%%%%%%%%
    [path,name,ext] = fileparts(which(mfilename));
    addpath(path,fullfile(path,'common_files'),...
        fullfile(path,'common_files','index_data'));

    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    [StartFigTextColor,StartFigBackColor,OutputFigTextColor,OutputFigBackColor,...
        ButtonTextColor,ButtonBackColor,EditTextColor,EditBackColor,...
        FrameTextColor,FrameBackColor,FontName,FontUnits,FontWeight,FontAngle,...
        TitleTextFontSize,HeaderTextFontSize,BodyTextFontSize,Body2TextFontSize,...
        SmallTextFontSize,ButtonFontSize,SmallButtonFontSize,...
        StartFigWidth,StartFigHt,OutputFigWidth,OutputFigHt]=lfosr_fontscolors;

    figLeft       = 132;
    figBottom     = 48;
    figWidth      = StartFigWidth;
    figHt         = StartFigHt;

    center        = 0.5;
    spacing1      = 0.07;
    spacing2      = 0.015;
    spacing3      = 0.0001;
    marginleft    = 0.086;

    txtWidth      = 0.22;
    txtHt         = 0.04;
    bigtxtHt      = 0.05;

    buttonBottom  = 0.07;
    buttonWidth   = 0.17;
    buttonHt      = 0.06;

    editWidth     = 0.10;
    editHt        = 0.06;

    radioWidth    = 0.20;
    radioHt       = 0.04;

    %%%%%%%%%%%%%%%%% PROGRAM INPUT CONTROL %%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %path and name of file plus Text Extension
    f_location_home = which('film_defaults.txt');
    f_location_default = fullfile(path,'common_files','film_defaults.txt');

    %
    % This code allows for multi-user systems where default files are in specific
    %  user files that are in the matlab path above LFOSR files.
    %
    if ~strcmp(f_location_home,f_location_default)
        f_location=f_location_home;
    else
        f_location=f_location_default;
    end

    fid        = fopen(f_location,'r');
    if fid==-1 %check for error on open
        error('Unable to open file.')
    end
    %
    Structure_file_location   = fgetl(fid);
    Start_lambdasweep_default = str2double(fgetl(fid));
    Stop_lambdasweep_default  = str2double(fgetl(fid));
    Start_thetasweep_default  = str2double(fgetl(fid));
    Stop_thetasweep_default   = str2double(fgetl(fid));
    Start_layersweep_default  = str2double(fgetl(fid));
    Stop_layersweep_default   = str2double(fgetl(fid));
    Points_value_default      = str2double(fgetl(fid));
    Angle_value_default       = str2double(fgetl(fid));
    Wavelength_value_default  = str2double(fgetl(fid));
    Layer_value_default       = str2double(fgetl(fid));
    Length_value_default      = str2double(fgetl(fid));
    %
    Lambda_default            = str2double(fgetl(fid));
    Theta_default             = str2double(fgetl(fid));
    A_Length_default          = str2double(fgetl(fid));
    %
    Slider_Bar_default        = str2double(fgetl(fid));
    Percentage_Length_default = str2double(fgetl(fid));
    Timedebug_default         = str2double(fgetl(fid));
    %
    fclose(fid);
    %
    sweep_choice = 100*Lambda_default+10*Theta_default+1*A_Length_default;

    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    handle = figure('Color',StartFigBackColor, ...
        'Name',['LFOSR FilmCalc v',num2str(LFOSRVersion)],...
        'NumberTitle','off',...
        'Menubar','none',...
        'Position',[figLeft figBottom figWidth figHt],...
        'Tag','FILM','Visible','off','Pointer','watch');


    if versionnumber<5.3
        set(handle,'HandleVisibility','callback')
    elseif versionnumber>=5.3&&versionnumber<6.0
        set(handle,'HandleVisibility','callback','HitTest','off')
    elseif versionnumber>=6.0&&versionnumber<6.5
        set(handle,'HandleVisibility','callback')
    elseif versionnumber>=6.5
        set(handle,'Resize','off')  %didn't work in WinXP in previous versions
    end
    %%%%%%%%%%%%%%%%%%%%%%%%%%% Headings %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %%%%%%%%% Title %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    uicontrol('Parent',handle, ...
        'Units','normalized', ...
        'BackgroundColor',StartFigBackColor, ...
        'ForegroundColor',StartFigTextColor,...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',TitleTextFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','center', ...
        'Position',[0 .93 1 bigtxtHt], ...
        'String','Layered Film Optical Simulation Routine', ...
        'Style','text');
    uicontrol('Parent',handle, ...
        'Units','normalized', ...
        'BackgroundColor',StartFigBackColor, ...
        'ForegroundColor',StartFigTextColor,...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',TitleTextFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','center', ...
        'Position',[0 .88 1 bigtxtHt], ...
        'String',['Film Calculation - Version ',num2str(LFOSRVersion)], ...
        'Style','text');
    %%%%%%%%%%%% Headings %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    uicontrol('Parent',handle, ...
        'Units','normalized', ...
        'BackgroundColor',StartFigBackColor, ...
        'ForegroundColor',StartFigTextColor,...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',BodyTextFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','left', ...
        'Position',[marginleft .803 .28 bigtxtHt], ...
        'String','Choose Structure File', ...
        'Style','text');

    uicontrol('Parent',handle, ...
        'Units','normalized', ...
        'BackgroundColor',StartFigBackColor, ...
        'ForegroundColor',StartFigTextColor,...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',BodyTextFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','left', ...
        'Position',[marginleft .526 .28 bigtxtHt], ...
        'String','Choose Sweep Variable', ...
        'Style','text');

    uicontrol('Parent',handle, ...
        'Units','normalized', ...
        'BackgroundColor',StartFigBackColor, ...
        'ForegroundColor',StartFigTextColor,...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',BodyTextFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','left', ...
        'Position',[center-.07 .276 .28 bigtxtHt], ...
        'String','Choose Layer', ...
        'Style','text');

    uicontrol('Parent',handle, ...
        'Units','normalized', ...
        'BackgroundColor',StartFigBackColor, ...
        'ForegroundColor',StartFigTextColor,...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',BodyTextFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','left', ...
        'Position',[marginleft .276 .24 bigtxtHt], ...
        'String','Program Information', ...
        'Style','text');

    uicontrol('Parent',handle, ...
        'Units','normalized', ...
        'BackgroundColor',StartFigBackColor, ...
        'ForegroundColor',StartFigTextColor,...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',SmallTextFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','center', ...
        'Position',[.35 .485 .3 txtHt], ...
        'String','(All lengths given in nanometers!)', ...
        'Style','text');

    Percentage_Length = uicontrol('Parent',handle, ...
        'Units','normalized', ...
        'BackgroundColor',StartFigBackColor, ...
        'ForegroundColor',StartFigTextColor,...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',ButtonFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','left', ...
        'Position',[center-.10+2*(radioWidth+spacing3) .485 1.6*radioWidth radioHt], ...
        'String','Length by %', ...
        'Value',Percentage_Length_default,...
        'Style','checkbox', ...
        'Tag','Film_Percentage_Length');

    userselect_h2 = uicontrol('Parent',handle, ...
        'Units','normalized', ...
        'BackgroundColor',StartFigBackColor, ...
        'ForegroundColor',StartFigTextColor,...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',SmallTextFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','center', ...
        'Position',[0 0.01 1 txtHt], ...
        'Style','text', ...
        'String',['User Run Option - ',upper(user_selection)],...
        'Tag','Film_User_selection');
    if user_run
        set(userselect_h2,'Visible','on');
    else
        set(userselect_h2,'Visible','off');
    end

    %%%%%%%%%%% Sweep Variable %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    Lambda = uicontrol('Parent',handle, ...
        'Units','normalized', ...
        'BackgroundColor',StartFigBackColor, ...
        'ForegroundColor',StartFigTextColor,...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',ButtonFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','left', ...
        'Position',[center-.10 .529 radioWidth radioHt], ...
        'String','Lambda', ...
        'Value',Lambda_default,...
        'Style','radiobutton', ...
        'Tag','Film_Lambda');

    Theta = uicontrol('Parent',handle, ...
        'Units','normalized', ...
        'BackgroundColor',StartFigBackColor, ...
        'ForegroundColor',StartFigTextColor,...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',ButtonFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','left', ...
        'Position',[center-.10+(radioWidth+spacing3) .529 radioWidth radioHt], ...
        'String','Theta', ...
        'Value',Theta_default,...
        'Style','radiobutton', ...
        'Tag','Film_Theta');

    A_Length = uicontrol('Parent',handle, ...
        'Units','normalized', ...
        'BackgroundColor',StartFigBackColor, ...
        'ForegroundColor',StartFigTextColor,...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',ButtonFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','left', ...
        'Position',[center-.10+2*(radioWidth+spacing3) .529 radioWidth radioHt], ...
        'String','Layer Thickness', ...
        'Value',A_Length_default,...
        'Style','radiobutton', ...
        'Tag','Film_A_Length');

    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    uicontrol('Parent',handle, ...
        'Units','normalized', ...
        'BackgroundColor',StartFigBackColor, ...
        'ForegroundColor',StartFigTextColor,...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',HeaderTextFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','left', ...
        'Position',[marginleft .38+editHt txtWidth txtHt], ...
        'String','Start Value', ...
        'Style','text');
    Start = uicontrol('Parent',handle, ...
        'Units','normalized', ...
        'BackgroundColor',EditBackColor, ...
        'ForegroundColor',EditTextColor,...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',HeaderTextFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','left', ...
        'Position',[marginleft .38 editWidth editHt], ...
        'Style','edit', ...
        'Tag','Film_Start');

    uicontrol('Parent',handle, ...
        'Units','normalized', ...
        'BackgroundColor',StartFigBackColor, ...
        'ForegroundColor',StartFigTextColor,...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',HeaderTextFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','left', ...
        'Position',[marginleft+1*(editWidth+spacing1) .38+editHt txtWidth txtHt], ...
        'String','End Value', ...
        'Style','text');
    Stop = uicontrol('Parent',handle, ...
        'Units','normalized', ...
        'BackgroundColor',EditBackColor, ...
        'ForegroundColor',EditTextColor,...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',HeaderTextFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','left', ...
        'Position',[marginleft+1*(editWidth+spacing1) .38 editWidth editHt], ...
        'Style','edit', ...
        'Tag','Film_Stop');

    uicontrol('Parent',handle, ...
        'Units','normalized', ...
        'BackgroundColor',StartFigBackColor, ...
        'ForegroundColor',StartFigTextColor,...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',HeaderTextFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','left', ...
        'Position',[marginleft+2*(editWidth+spacing1) .38+editHt txtWidth txtHt], ...
        'String','Data Points', ...
        'Style','text');
    uicontrol('Parent',handle, ...  %Points =
        'Units','normalized', ...
        'BackgroundColor',EditBackColor, ...
        'ForegroundColor',EditTextColor,...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',HeaderTextFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','left', ...
        'Position',[marginleft+2*(editWidth+spacing1) .38 editWidth editHt], ...
        'Style','edit', ...
        'String',Points_value_default,...
        'Tag','Film_Points');

    uicontrol('Parent',handle, ...
        'Units','normalized', ...
        'BackgroundColor',StartFigBackColor, ...
        'ForegroundColor',StartFigTextColor,...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',HeaderTextFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','left', ...
        'Position',[marginleft+3*(editWidth+spacing1) .38+editHt txtWidth txtHt], ...
        'String','Incident Angle',...
        'Style','text');
    Angle = uicontrol('Parent',handle, ...
        'Units','normalized', ...
        'BackgroundColor',EditBackColor, ...
        'ForegroundColor',EditTextColor,...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',HeaderTextFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','left', ...
        'Position',[marginleft+3*(editWidth+spacing1) .38 editWidth editHt], ...
        'Style','edit', ...
        'String',Angle_value_default,...
        'Tag','Film_Angle');

    uicontrol('Parent',handle, ...
        'Units','normalized', ...
        'BackgroundColor',StartFigBackColor, ...
        'ForegroundColor',StartFigTextColor,...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',HeaderTextFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','left', ...
        'Position',[marginleft+4*(editWidth+spacing1) .38+editHt txtWidth txtHt], ...
        'String','Incident Wavelength',...
        'Style','text');
    Wavelength = uicontrol('Parent',handle, ...
        'Units','normalized', ...
        'BackgroundColor',EditBackColor, ...
        'ForegroundColor',EditTextColor,...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',HeaderTextFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','left', ...
        'Position',[marginleft+4*(editWidth+spacing1) .38 editWidth editHt], ...
        'Style','edit', ...
        'String',Wavelength_value_default,...
        'Tag','Film_Wavelength');

    Length_text = uicontrol('Parent',handle, ...
        'Units','normalized', ...
        'BackgroundColor',StartFigBackColor, ...
        'ForegroundColor',StartFigTextColor,...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',HeaderTextFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','left', ...
        'Position',[center-.07+txtWidth .276-(txtHt+spacing2) txtWidth+.05 txtHt], ...
        'String','Length Layer Number', ...
        'Style','text');
    Length = uicontrol('Parent',handle, ...
        'Units','normalized', ...
        'BackgroundColor',EditBackColor, ...
        'ForegroundColor',EditTextColor,...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',HeaderTextFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','left', ...
        'Position',[center-.07+txtWidth .276-(editHt+spacing2+txtHt) editWidth editHt], ...
        'Style','edit', ...
        'String',Length_value_default,...
        'Tag','Film_Length');

    Layer_text = uicontrol('Parent',handle, ...
        'Units','normalized', ...
        'BackgroundColor',StartFigBackColor, ...
        'ForegroundColor',StartFigTextColor,...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',HeaderTextFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','left', ...
        'Position',[center-.07 .276-(txtHt+spacing2) txtWidth txtHt], ...
        'String','Layer Number',...
        'Style','text');
    Layer = uicontrol('Parent',handle, ...
        'Units','normalized', ...
        'BackgroundColor',EditBackColor, ...
        'ForegroundColor',EditTextColor,...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',HeaderTextFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','left', ...
        'Position',[center-.07 .276-(editHt+spacing2+txtHt) editWidth editHt], ...
        'Style','edit', ...
        'String',Layer_value_default,...
        'Tag','Film_Layer');

    if strcmpi(user_selection,'biosensor')
        set(Layer_text,'String','Bio Layer Number')
        set(Layer,'Enable','on')
    elseif strcmpi(user_selection,'textured')
        set(Layer_text,'String','Textured Layer Number')
        set(Layer,'Enable','on')
    else
        set(Layer_text,'String','Not Used')
        set(Layer,'Enable','off')
    end

    %              1      2     3        4     5    6     7          8
    %   9      10
    %   11                       12
    %   13                       14
    %   15             Lambda          16f
    Radio_Handles={Lambda Theta A_Length Start Stop Angle Wavelength Layer ...
        Length Percentage_Length Start_lambdasweep_default Stop_lambdasweep_default ...
        Start_thetasweep_default Stop_thetasweep_default ...
        Start_layersweep_default Stop_layersweep_default};

    switch sweep_choice
        case 100 %lambda sweep
            lfosr_guivalues(handle,Lambda,Radio_Handles)
        case 10 %theta sweep
            lfosr_guivalues(handle,Theta,Radio_Handles)
        case 1 %layer sweep
            lfosr_guivalues(handle,A_Length,Radio_Handles)
    end

    set(  Lambda,'UserData',Radio_Handles)
    set(   Theta,'UserData',Radio_Handles)
    set(A_Length,'UserData',Radio_Handles)

    set(  Lambda,'CallBack','lfosr_guivalues(gcbf,gcbo,get(gcbo,''Userdata''))')
    set(   Theta,'CallBack','lfosr_guivalues(gcbf,gcbo,get(gcbo,''Userdata''))')
    set(A_Length,'CallBack','lfosr_guivalues(gcbf,gcbo,get(gcbo,''Userdata''))')

    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    %%%%%%%% Structure File %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    default = uicontrol('Parent',handle, ...
        'Units','normalized', ...
        'BackgroundColor',StartFigBackColor, ...
        'ForegroundColor',StartFigTextColor,...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',ButtonFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','left', ...
        'Position',[center .806 1.4*radioWidth radioHt], ...
        'String','Default Structure File', ...
        'Style','radiobutton');

    no_default = uicontrol('Parent',handle, ...
        'Units','normalized', ...
        'BackgroundColor',StartFigBackColor, ...
        'ForegroundColor',StartFigTextColor,...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',ButtonFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','left', ...
        'Position',[center .730 1.4*radioWidth radioHt], ...
        'String','Select Structure File', ...
        'Style','radiobutton');

    Path = uicontrol('Parent',handle, ...
        'Units','normalized', ...
        'BackgroundColor',EditBackColor, ...
        'ForegroundColor',EditTextColor,...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',HeaderTextFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','left', ...
        'Position',[center .635 .417 buttonHt], ...
        'String',Structure_file_location, ...
        'Style','edit', ...
        'Tag','Film_Path');

    Edit_structure = uicontrol('Parent',handle, ...
        'Units','normalized', ...
        'BackgroundColor',ButtonBackColor, ...
        'ForegroundColor',ButtonTextColor,...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',ButtonFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'Position',[marginleft .635 1.5*buttonWidth buttonHt], ...
        'String','Edit Structure File');

    if strcmp(Structure_file_location,'structure.txt')
        set(default,'Value',1)
        set(no_default,'Value',0)
    else
        set(default,'Value',0)
        set(no_default,'Value',1)
    end

    set(       default,'UserData',[default no_default Path Edit_structure])
    set(    no_default,'UserData',[default no_default Path Edit_structure])
    set(          Path,'UserData',[default no_default Path Edit_structure])
    set(Edit_structure,'UserData',[default no_default Path Edit_structure])

    set(       default,'CallBack','structure_select(gcbo,get(gcbo,''UserData''))')
    set(    no_default,'CallBack','structure_select(gcbo,get(gcbo,''UserData''))')
    set(          Path,'CallBack','structure_select(gcbo,get(gcbo,''UserData''))')
    set(Edit_structure,'CallBack','structure_select(gcbo,get(gcbo,''UserData''))')

    %%%%%%%%%% Output Graphs %%%%%%%%%%%%%%%%%%%%%%%%%%%%
    uicontrol('Parent',handle, ...  %Slider_Bar =
        'Units','normalized', ...
        'BackgroundColor',StartFigBackColor, ...
        'ForegroundColor',StartFigTextColor,...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',ButtonFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','left', ...
        'Position',[marginleft .276-(radioHt+spacing2) 1.6*radioWidth radioHt], ...
        'String','Show Thickness Slider Bar', ...
        'Value',Slider_Bar_default,...
        'Style','checkbox', ...
        'Tag','Film_Slider_Bar');
    %if user_run
    %    set(Slider_Bar,'Visible','off');
    %else
    %    set(Slider_Bar,'Visible','on');
    %end

    uicontrol('Parent',handle, ...  %Timedebug =
        'Units','normalized', ...
        'BackgroundColor',StartFigBackColor, ...
        'ForegroundColor',StartFigTextColor,...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',ButtonFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','left', ...
        'Position',[marginleft .276-2*(radioHt+spacing2) 1.6*radioWidth radioHt], ...
        'String','Show Program Time Information', ...
        'Value',Timedebug_default,...
        'Style','checkbox', ...
        'Tag','Film_Timedebug');

    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    uicontrol('Parent',handle, ...
        'Units','normalized', ...
        'BackgroundColor',ButtonBackColor, ...
        'ForegroundColor',ButtonTextColor,...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',ButtonFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'Position',[center-2*(buttonWidth+2*spacing2)-buttonWidth/2 buttonBottom buttonWidth buttonHt], ...
        'String','Start',...
        'Callback','film(''run'')');

    uicontrol('Parent',handle, ...
        'Units','normalized', ...
        'BackgroundColor',ButtonBackColor, ...
        'ForegroundColor',ButtonTextColor,...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',ButtonFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'Position',[center-1*(buttonWidth+2*spacing2)-buttonWidth/2 buttonBottom buttonWidth buttonHt], ...
        'String','Web Help', ...
        'Callback','film(''web'')');

    uicontrol('Parent',handle, ...
        'Units','normalized', ...
        'BackgroundColor',ButtonBackColor, ...
        'ForegroundColor',ButtonTextColor,...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',ButtonFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'Position',[center-0*(buttonWidth+2*spacing2)-buttonWidth/2 buttonBottom buttonWidth buttonHt], ...
        'String','Check Version', ...
        'Callback','film(''version'')');

    uicontrol('Parent',handle, ...
        'Units','normalized', ...
        'BackgroundColor',ButtonBackColor, ...
        'ForegroundColor',ButtonTextColor,...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',ButtonFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'Position',[center-0*(buttonWidth+2*spacing2)+buttonWidth/2+2*spacing2 buttonBottom buttonWidth buttonHt], ...
        'String','Save Settings', ...
        'Callback','film(''save'')');

    uicontrol('Parent',handle, ...
        'Units','normalized', ...
        'BackgroundColor',ButtonBackColor, ...
        'ForegroundColor',ButtonTextColor,...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',ButtonFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'Position',[center+1*(buttonWidth+2*spacing2)+buttonWidth/2+2*spacing2,...
        buttonBottom buttonWidth buttonHt], ...
        'String','Close', ...
        'Callback','film(''close'')');

    set(handle,'Visible','on','Pointer','arrow')
    drawnow;
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %%%%%%%%%%%%%%%% END INITIALIZE PROGRAM INTERFACE %%%%%%%%%%%%%%%%%%%%%
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %%%%%%%%%%%%%%%%%%%%%%% RUN PROGRAM FILM ROUTINE %%%%%%%%%%%%%%%%%%%%%%
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%